spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/acm
    username: acmsecy
    password: acmheads
    hikari:
      connectionTimeout: 10000
      maximumPoolSize: 5
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email
    password: your_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true