spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/acm
    username: acmsecy
    password: acmheads
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect