server:
  port: 8080
spring:
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:postgresql://db.bujnagbmqjzifgmqsxkc.supabase.co:5432/postgres
    username: postgres
    password: 53zIJPwXo9qzoSw8
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: acmcss@pec.edu.in
    password: pzsdhgeqmjtnbdpp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#  sql:
#    init:
#      mode: always
verify:
  base:
    frontend: http://localhost:3000/